# Generated by Django 3.2.9 on 2021-11-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musics', '0002_auto_20211104_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('name_playlist', models.CharField(max_length=255)),
                ('Music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='musics.musics')),
            ],
            options={
                'db_table': 'playlists',
                'managed': True,
                'unique_together': {('name_playlist', 'Music')},
            },
        ),
    ]
