# Generated by Django 3.2.9 on 2021-11-04 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id_music', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_music', models.CharField(max_length=255)),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artists')),
            ],
        ),
    ]
