# Generated by Django 3.2.9 on 2021-11-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20211104_2022'),
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musics',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='musics',
            name='Artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artista', to='artists.artists'),
        ),
        migrations.AlterUniqueTogether(
            name='musics',
            unique_together={('name_music', 'Artist')},
        ),
        migrations.AlterModelTable(
            name='musics',
            table='Musics',
        ),
    ]
