# Generated by Django 3.2.9 on 2021-11-04 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id_artist', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Artist', models.CharField(max_length=255)),
                ('Style', models.CharField(max_length=255)),
            ],
        ),
    ]
