# Generated by Django 3.2.9 on 2021-11-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='artists',
            unique_together={('Artist', 'Style')},
        ),
        migrations.AlterModelTable(
            name='artists',
            table='Artists',
        ),
    ]
